apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-scan
spec:
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarscan-01
        image: sonarqube
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
