apiVersion: v1
kind: Pod
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  containers:
  - name: sonarqube
    image: sonarqube
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9000